server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:https://github.com/loicosquare/microservice-tech-config-server}
          clone-on-start: true

#Pour quoi on a besoin de cette configuration? pour que le config server puisse se connecter à l'eureka server (Service Registry).
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://172.22.144.1:8761/eureka} # This line use the environment variable EUREKA_SERVER_ADDRESS to get the host of the eureka server otherwise it will use localhost
  instance:
    prefer-ip-address: true