version: '3'

services:
  serviceregistry:
#    image: 'svc-registry:1.0.0'
    build:
      context: ./ServiceRegistry
      dockerfile: Dockerfile
    container_name: svc-registry
    ports:
      - '8761:8761'

  configserver:
    #image: 'svc-configserver:1.0.0'
    build:
      context: ./ConfigServer
      dockerfile: Dockerfile
    container_name: svc-configserver
    ports:
      - '8085:8085'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    #healthcheck:
#      test: ["CMD", "curl", "-f", "http://configserver:8085/actuator/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    depends_on:
      - serviceregistry

  apigateway:
    image: 'loicsanou/svc-apigateway:1.0.0'
#    build:
#      context: ./ApiGateway
#      dockerfile: Dockerfile
    container_name: svc-apigateway
    ports:
      - '8084:8084'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      - configserver
        #condition: service_healthy

#  userservice:
#    image: 'svc-userservice:1.0.0'
#    container_name: svc-userservice
#    ports:
#      - '8080:8080'
#    environment:
#      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
#      - CONFIG_SERVER_URL=configserver
#    depends_on:
#      configserver:
#        condition: service_healthy
#
#  categoryservice:
#    image: 'svc-categoryservice:1.0.0'
#    container_name: svc-categoryservice
#    ports:
#      - '8081:8081'
#    environment:
#      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
#      - CONFIG_SERVER_URL=configserver
#    depends_on:
#      configserver:
#        condition: service_healthy

#  gameservice:
#    image: 'svc-gameservice:1.0.0'
#    container_name: svc-gameservice
#    ports:
#      - '8082:8082'
#    environment:
#      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
#      - CONFIG_SERVER_URL=configserver
#    depends_on:
#      configserver:
#        condition: service_healthy

#  ratingservice:
#    image: 'svc-ratingservice:1.0.0'
#    container_name: svc-ratingservice
#    ports:
#      - '8083:8083'
#    environment:
#      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
#      - CONFIG_SERVER_URL=configserver
#    depends_on:
#      configserver:
#        condition: service_healthy

#  enterpriseservice:
#    image: 'svc-enterpriseservice:1.0.0'
#    container_name: svc-enterpriseservice
#    ports:
#      - '8086:8086'
#    environment:
#      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
#      - CONFIG_SERVER_URL=configserver
#    depends_on:
#      configserver:
#        condition: service_healthy