server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel-service
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: HOTEL-SERVICE