server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: rating-service
  application:
    name: RATING-SERVICE
  config:
    import: configserver:http://localhost:8085


#Etape 4 de notre fichier contenant le guide des étapes à suivre pour la mise en place de notre microservice
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    userService-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka} # This line use the environment variable EUREKA_SERVER_ADDRESS to get the host of the eureka server otherwise it will use localhost