server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: rating-service
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085/


#Etape 4 de notre fichier contenant le guide des étapes à suivre pour la mise en place de notre microservice
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    userService-url:
#      defaultzone: http://localhost:8761/eureka