server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: category-service
  application:
    name: CATEGORY-SERVICE
  config:
    import: optional:configserver:http://localhost:8085/